### ISSUE TITLE
React.Fragment

### ISSUE THREAD

**Issue by seejamescode** [Hebilicious/gatsby-remark-component#1]
Hi @Hebilicious, and thanks for contributing to https://github.com/gatsbyjs/gatsby/issues/312!

I understand that so far implementations use dangerouslySetInnerHTML, so they need to be HTML instead of JSX. Is there a way we could flatten the HTML out so that we don’t even wrap React components in a `div`? Could we utilize [`<React.Fragment>`](https://reactjs.org/docs/fragments.html) in some way?

**Comment by Hebilicious** [comment]
Hi @seejamescode, I looked into gatsby-transformer-remark [source](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark) and it doesn't use dangerouslySetInnerHTML, so I don't think we could use React.Fragment in this plugin, unless I'm missing something? In #https://github.com/gatsbyjs/gatsby/issues/312 some people proposed more advanced solutions to parse markdown that might allow that, however if the idea is to not have any wrapper around an markdown component, I believe we could tweak the generated AST and instead of this
```js
{
  "type": "element",
  "tagName": "div",
  "properties": {},
  "children": [
    {
      "type": "element",
      "tagName": "my-component",
      "properties": {},
      "children": []
    }
  ]
}
```
directly get this
```js
{
      "type": "element",
      "tagName": "my-component",
      "properties": {},
      "children": []
}
```

**Comment by seejamescode** [comment]
^ That would be beautiful. My assumption is that would be the desired default behavior. However, I am probably mistaken. Could we expose this object in the plugin options?

**Comment by macandcheese** [comment]
@Hebilicious @seejamescode that's definitely the desired behavior... Changing the <p> wrapper to a <div> is nice, but being able to directly insert your custom component wrapped in a <Fragment> would be ideal.

**Comment by misterbridge** [comment]
@rstacruz @baobabKoodaa I'll post this here because I couldn't find a way to fill issues in your repos.

Actually I think there is another solution which might please everyone and that is really simple to implement. I'd propose a PR if you say you'll merge it: Add an option for a custom tag instead of just a div.

(That's like a 3 lines PR)

People will not only be able to place any tag they want, but they would also be able to use it like so:

```javascript
plugins: [
  {
    resolve: "gatsby-transformer-remark",
    options: {
      plugins: [
        {
          resolve: "gatsby-remark-component",
          options: { customTag: "fragment" }
        }
      ]
    }
  }
]
```

```jsx
import React from "react"
import rehypeReact from "rehype-react"

const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: {
    fragment: (props) => (
      <React.Fragment {...props} />
    ),
  }
}).Compiler
```

Which would lead to the desired "no wrapper" behaviour.

**Comment by baobabKoodaa** [comment]
Hi @misterbridge ! This seems like a fine idea and I appreciate your contribution. Unfortunately I'm a little hesitant to spend time on this because nobody is using my fork. Sorry! Feel free to make (another) fork though :)
